import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useWorkspace } from '../data/Workspace';
import { Badge, DataGate, date } from '../components/ui';
import Raster from '../components/Raster';
import { PairControls } from './Explore';
import { preparePair } from '../../shared/analysis';
export default function Compare(){return <DataGate><Comparison/></DataGate>;}
function Comparison(){const w=useWorkspace(),d=w.dataset!,[requestedMode,setMode]=useState('swipe'),[split,setSplit]=useState(50),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});const {before,after}=preparePair(d,w.before,w.after,w.filter);const mode=requestedMode==='difference'&&!w.result?'swipe':requestedMode;
 return <div className="page"><div className="page-heading"><div><span className="tiny">Same grid. Two moments.</span><h1>Before / after</h1></div><Badge observed={d.status==='observed'}/></div><p className="lead">Compare the signal before interpreting the story. Both views share their scale, position, and display range.</p><div className="comparison-layout"><aside className="panel"><h2>{d.location}</h2><PairControls/><button onClick={()=>w.setEvidence(true)}>Inspect pair evidence</button><p className="tiny">Display range: −24 to −4 dB. Gray cells are excluded. {d.status==='synthetic'?'Discrete synthetic grid, not satellite imagery.':''}</p></aside><section className="panel compare-panel"><div className="segmented">{['swipe','opacity','difference'].map(m=><button key={m} aria-pressed={mode===m} className={mode===m?'active':''} disabled={m==='difference'&&!w.result} onClick={()=>setMode(m)}>{m}</button>)}</div><div className="compare-labels"><span>Before · {date(d.observations[w.before].date)}</span><span>After · {date(d.observations[w.after].date)}</span></div><div className="compare-stage" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.buttons===1&&zoom>1)setPan(p=>({x:Math.max(-150,Math.min(150,p.x+e.movementX)),y:Math.max(-150,Math.min(150,p.y+e.movementY))}));}}>
 <div className="compare-transform" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>{mode==='difference'&&w.result?<Raster values={w.result.delta} width={d.width} height={d.height} lens="difference" label="Computed difference grid"/>:<><Raster values={before} width={d.width} height={d.height} label="Before observation grid"/><div className="compare-overlay" style={mode==='swipe'?{clipPath:`inset(0 0 0 ${split}%)`}:{opacity:split/100}}><Raster values={after} width={d.width} height={d.height} label="After observation grid"/></div></>}</div>{mode==='swipe'&&<div className="swipe-line" style={{left:`${split}%`}}><span>↔</span></div>}<span className="raster-caption">{d.status==='synthetic'?'Synthetic teaching grid':'Imported GCOV window'} · common coordinates</span></div>
 {mode!=='difference'&&<label className="range-label">{mode==='swipe'?'Swipe position':'After opacity'}<input aria-label={mode==='swipe'?'Swipe position':'After opacity'} type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))}/></label>}
 <label className="range-label">Synchronized zoom · drag to pan<input aria-label="Synchronized zoom" type="range" min="1" max="3" step="0.1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><div className="actions"><button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>Reset view</button><Link className="button primary" to="/analysis">Interpret change</Link></div></section></div></div>;}
