import { lazy, Suspense, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, FlaskConical, ShieldCheck, Search, SlidersHorizontal } from 'lucide-react';
import type { Bounds, Lens, CatalogRecord } from '../../shared/schema';
import { useWorkspace } from '../data/Workspace';
import { provider } from '../data/providers';
import { Badge, DataGate, date, External } from '../components/ui';
import Timeline from '../components/Timeline';
import { TemporalChart } from '../components/Charts';
import AskData from '../components/AskData';
const GeoMap=lazy(()=>import('../components/GeoMap'));
const lenses:{id:Lens;label:string}[]=[{id:'raw',label:'Input power'},{id:'processed',label:'Processed'},{id:'difference',label:'Difference'},{id:'detected',label:'Change mask'},{id:'uncertainty',label:'Uncertainty'}];

export function PairControls(){const w=useWorkspace(),d=w.dataset!;return <><div className="pair-controls"><label>Before<select value={w.before} onChange={e=>w.setBefore(Number(e.target.value))}>{d.observations.map((o,i)=><option key={o.id} value={i} disabled={i>=w.after}>{date(o.date)}</option>)}</select></label><label>After<select value={w.after} onChange={e=>w.setAfter(Number(e.target.value))}>{d.observations.map((o,i)=><option key={o.id} value={i} disabled={i<=w.before}>{date(o.date)}</option>)}</select></label></div><label className="range-label">Change threshold <strong>{w.threshold.toFixed(1)} dB</strong><input aria-label="Change threshold" type="range" min="0.5" max="10" step="0.5" value={w.threshold} onChange={e=>w.setThreshold(Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={w.filter} onChange={e=>w.setFilter(e.target.checked)}/>3 × 3 mean in linear power</label><p className="tiny">Threshold is exploratory, not calibrated to event probability.</p><button className="primary run" disabled={w.analyzing} onClick={w.run}><FlaskConical size={17}/>{w.analyzing?'Analyzing…':'Run analysis'}</button>{w.analysisError&&<div role="alert" className="notice">{w.analysisError}<button onClick={w.run}>Retry analysis</button></div>}</>;}

export default function Explore(){return <DataGate><ExploreContent/></DataGate>;}
function ExploreContent(){const w=useWorkspace(),d=w.dataset!,location=useLocation();const [query,setQuery]=useState(''),[phenomenon,setPhenomenon]=useState('all'),[searchMessage,setSearchMessage]=useState(''),[aoi,setAoi]=useState<Bounds|null>(null),[records,setRecords]=useState<CatalogRecord[]|null>(null),[catalogError,setCatalogError]=useState(''),[catalogLoading,setCatalogLoading]=useState(false);
 const isTime=location.pathname==='/time-machine';const filtered=w.datasets.filter(x=>(phenomenon==='all'||x.phenomenon===phenomenon)&&`${x.location} ${x.title}`.toLowerCase().includes(query.toLowerCase()));
 async function discover(){setCatalogLoading(true);setCatalogError('');setRecords(null);try{const data=await provider.catalog(aoi??d.bounds);setRecords(data.records);}catch(e){setCatalogError(e instanceof Error?e.message:'Discovery failed');}finally{setCatalogLoading(false);}}
 function search(){const parts=query.split(',').map(Number);if(parts.length===2&&parts.every(Number.isFinite)&&Math.abs(parts[0])<=84.75&&Math.abs(parts[1])<=179.75){const [lat,lon]=parts;setAoi([lon-.25,lat-.25,lon+.25,lat+.25]);setSearchMessage(`Discovery region set to ${lat}, ${lon}. Use Search NASA catalog.`);}else setSearchMessage(filtered.length?`${filtered.length} study areas match.`:'No prepared study matches. Enter latitude, longitude to search the NASA catalog.');}
 const metric=w.result;
 return <div className="explore-page"><div className="page-heading"><div><span className="tiny">Surface change workspace</span><h1>{isTime?'Earth time machine':'Explore Earth'}</h1></div><div className="actions"><Badge observed={d.status==='observed'}/><button onClick={()=>w.setEvidence(true)}><ShieldCheck size={16}/>Inspect evidence</button></div></div>
 <div className="workspace"><aside className="sidebar"><h2>Your study area</h2><form className="search" onSubmit={e=>{e.preventDefault();search();}}><label className="sr-only" htmlFor="location-search">Search location or latitude, longitude</label><input id="location-search" placeholder="Location or lat, lon" value={query} onChange={e=>setQuery(e.target.value)}/><button aria-label="Search location" type="submit"><Search size={17}/></button></form>{searchMessage&&<p className="tiny" role="status">{searchMessage}</p>}
 <label>Phenomenon<select value={phenomenon} onChange={e=>setPhenomenon(e.target.value)}><option value="all">All supported workflows</option><option value="wetland">Wetland / water change</option><option value="agriculture">Agricultural change</option><option value="disturbance">Surface disturbance</option></select></label>
 <div className="study-list">{filtered.map(x=><button key={x.id} className={d.id===x.id?'active':''} aria-pressed={d.id===x.id} onClick={()=>{w.choose(x.id);setAoi(null);setRecords(null);setCatalogError('');}}><strong>{x.location.split(',')[0]}</strong><span>{x.phenomenon} · {x.observations.length} frames</span></button>)}{filtered.length===0&&<p className="tiny">No prepared study in this filter.</p>}</div>
 <div className="sidebar-detail"><span className="tiny">Selected location</span><strong>{d.location}</strong><span>{((d.bounds[1]+d.bounds[3])/2).toFixed(3)}°, {((d.bounds[0]+d.bounds[2])/2).toFixed(3)}°</span><span className="tiny">{d.status==='synthetic'?'Synthetic scenario; geographic context only.':'Imported acquisition series.'}</span></div>
 <h3><SlidersHorizontal size={16}/>Temporal comparison</h3><PairControls/>
 <div className="catalog-search"><h3>Real NISAR discovery</h3><p className="tiny">Search beta GCOV metadata for {aoi?'the clicked / entered region':'this study area'}. Coverage is collection-specific; no result is not proof of no NISAR coverage.</p><button disabled={catalogLoading} onClick={discover}>{catalogLoading?'Searching NASA…':'Search NASA catalog'}</button>{catalogError&&<p role="alert">{catalogError}<button onClick={discover}>Retry catalog</button></p>}{records&&<div role="status"><p>{records.length?`${records.length} actual records (up to 20 newest).`:'No NISAR beta GCOV observations returned for this region.'}</p>{records.slice(0,3).map(r=><External key={r.id} href={r.source}>{date(r.date)} · {r.id}</External>)}</div>}</div>
 </aside><div className="workspace-main"><div className="lens-bar"><strong>Change lens</strong><div role="group" aria-label="Change lens">{lenses.map(l=><button key={l.id} disabled={!metric&&['difference','detected','uncertainty'].includes(l.id)} title={!metric&&['difference','detected','uncertainty'].includes(l.id)?'Run analysis to enable this lens':undefined} aria-pressed={w.lens===l.id} className={w.lens===l.id?'active':''} onClick={()=>w.setLens(l.id)}>{l.label}</button>)}</div></div>
 <Suspense fallback={<div className="map-shell loading" role="status">Loading geographic workspace…</div>}><GeoMap onLocate={setAoi}/></Suspense>
 <div className="legend"><strong>{w.lens==='uncertainty'?'Threshold sensitivity, not probability':w.lens==='raw'?'Input linear power displayed in dB':w.lens==='processed'?'Processed power displayed in dB':'Δ backscatter (dB)'}</strong>{['raw','processed'].includes(w.lens)?<span><i className="swatch low"/>−24 dB <i className="swatch high"/>−4 dB · display clipped</span>:w.lens==='uncertainty'?<span><i className="swatch" style={{background:'#36576b'}}/>Above threshold, away from boundary <i className="swatch" style={{background:'#985b16'}}/>Within 0.5 dB of boundary <i className="swatch gray"/>Below threshold / excluded</span>:<span><i className="swatch blue"/>Decrease <i className="swatch amber"/>Increase <i className="swatch gray"/>Below threshold / excluded</span>}<span className="tiny">{['raw','processed'].includes(w.lens)?`Frame T${w.frame+1}`:`Pair T${w.before+1} → T${w.after+1} · fixed while timeline plays`}</span></div>
 <Timeline/>
 <div className="workspace-bottom"><TemporalChart/><div className="finding"><span className="tiny">{metric?'Algorithmic inference':'Ready to investigate'}</span><h2>{metric?'A change in signal. An open question.':'Move through time. Then compare.'}</h2><p>{metric?`${metric.changed} of ${metric.valid} valid cells cross your ${metric.threshold.toFixed(1)} dB threshold. This is evidence of numerical change in ${d.status==='synthetic'?'the teaching fixture':'the imported pair'}, not a confirmed event.`:`Frame T${w.frame+1} of ${d.observations.length} is visible. Select a before/after pair and run the comparison to reveal its difference and sensitivity.`}</p><Link className="text-link" to={metric?'/analysis':'/compare'}>{metric?'Interpret the analysis':'Open before / after'}<ArrowRight size={16}/></Link></div></div>
 </div></div><AskData/></div>;
}
