import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { observatorySchema, type Observatory } from '../../shared/observatory';
import { RegionWorkspace } from './Observatory';
export default function GlobalRadar(){
 const [params]=useSearchParams(),[lat,setLat]=useState(params.get('lat')??'28'),[lon,setLon]=useState(params.get('lon')??'85.3'),[query,setQuery]=useState(''),[places,setPlaces]=useState<{id:number;name:string;country?:string;latitude:number;longitude:number}[]>([]);
 const [data,setData]=useState<Observatory|null>(null),[status,setStatus]=useState('Choose a location, then discover its available radar dates.'),[busy,setBusy]=useState(false),[searchBusy,setSearchBusy]=useState(false),[searchMessage,setSearchMessage]=useState('');
 const active=useRef<AbortController|null>(null),searchActive=useRef<AbortController|null>(null);
 useEffect(()=>()=>{active.current?.abort();searchActive.current?.abort();},[]);
 async function discover(){active.current?.abort();const c=new AbortController();active.current=c;setBusy(true);setData(null);setStatus('Finding repeated NASA NISAR acquisitions…');try{const r=await fetch(`/api/global-radar?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,{signal:c.signal});const body=await r.json();if(!r.ok)throw Error(body.error);if(body.empty){setStatus(body.message);return;}const archive=observatorySchema.parse(body);setData(archive);setStatus(`${archive.regions[0].observations.length} acquisition dates found. Press Play observations below to animate.`);}catch(e){if(!c.signal.aborted)setStatus(e instanceof Error?e.message:'Discovery failed. Retry.');}finally{if(!c.signal.aborted)setBusy(false);}}
 async function search(){searchActive.current?.abort();const c=new AbortController();searchActive.current=c;setSearchBusy(true);setPlaces([]);setSearchMessage('Searching');try{const r=await fetch(`/api/places?q=${encodeURIComponent(query)}`,{signal:c.signal});const b=await r.json();if(!r.ok)throw Error(b.error);setPlaces(b.results);setSearchMessage(b.results.length?'Select a location.':'No places found. Use coordinates or another name.');}catch(e){if(!c.signal.aborted)setSearchMessage(e instanceof Error?e.message:'Search failed');}finally{if(!c.signal.aborted)setSearchBusy(false);}}
 return <><section className="page global-radar-search"><div className="section-heading"><div><span className="tiny">Search worldwide · animate available radar observations</span><h1>Any place. Through time.</h1></div><Link className="button" to="/world">Choose on the globe</Link></div><p>Find a place, discover its acquisition dates, then play or compare the real NISAR views. Coverage varies; missing observations are never invented.</p><form onSubmit={e=>{e.preventDefault();void search();}} className="actions"><label>Place name<input aria-label="Radar place search" required minLength={2} maxLength={100} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Dhaka, Kathmandu, Tokyo…"/></label><button disabled={searchBusy}>{searchBusy?'Searching…':'Find place'}</button></form><p role="status">{searchMessage}</p><div className="actions">{places.map(p=><button key={p.id} onClick={()=>{active.current?.abort();setBusy(false);setData(null);setLat(String(p.latitude));setLon(String(p.longitude));setStatus('Location selected. Discover radar dates to continue.');}}>{p.name}, {p.country}</button>)}</div><form className="actions" onSubmit={e=>{e.preventDefault();void discover();}}><label>Latitude<input aria-label="Radar latitude" type="number" step="any" required min="-84.8" max="84.8" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input aria-label="Radar longitude" type="number" step="any" required min="-179.8" max="179.8" value={lon} onChange={e=>setLon(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Discovering…':'Discover radar dates'}</button></form><p role="status">{status}</p><p className="tiny">Up to eight dates from a repeated catalog track/frame/mode. 1536 × 1536 NASA browse requests; not continuous video, optical photography, or quantitative change detection. Internet required.</p></section>{data&&<RegionWorkspace key={`${data.retrieved}-${data.regions[0].center.join()}`} data={data} region={data.regions[0]} choose={()=>{}}/>}</>;
}
