import { ArrowRight, Play, Layers, Fingerprint, Waves } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useWorkspace } from '../data/Workspace';
import { Badge } from '../components/ui';
import Raster from '../components/Raster';
import Timeline from '../components/Timeline';
export default function Home(){const w=useWorkspace(),d=w.dataset;return <div className="home"><section className="hero"><div className="hero-copy"><div className="mission-tag"><span/>An Earth observation workspace for NISAR</div><h1>See Earth<br/>Move.</h1><p>Earth’s surface never stands still.<br/>Follow its changes through radar observations, explore the evidence, and understand what the signal can—and can’t—tell us.</p><div className="actions"><Link className="button primary" to="/explore">Explore Earth<ArrowRight size={17}/></Link><Link className="button" to="/science">How it works</Link></div><div className="hero-footnote"><span>Built for “Dancing with the SARs”</span><span>NASA Space Apps 2026 · independent project</span></div></div><figure className="hero-image"><img src="/images/nisar-seattle.jpg" alt="Official NASA NISAR false-color radar visualization of Seattle and its waterways"/><div className="image-caption"><span>Earth, seen through radar.</span><small>NISAR Views Seattle · NASA/JPL-Caltech<br/>Official context image · not an analysis input</small></div><Link to="/data" className="image-source">Inspect source ↗</Link></figure></section>
 <section className="home-principles"><div><Waves/><strong>A different way to see</strong><p>Radar reveals changes in return strength. Interferometry can reveal motion under suitable conditions.</p></div><div><Layers/><strong>Time makes the difference</strong><p>Step through discrete frames, compare pairs, and investigate what changed.</p></div><div><Fingerprint/><strong>Evidence comes with it</strong><p>Source metadata, methods, and limitations stay connected to every result.</p></div></section>
 <section className="home-demo"><div className="home-demo-copy"><span className="tiny">Try the Earth time machine</span><h2>A landscape.<br/>More than one moment.</h2><p>Scrub the timeline to see a controlled change unfold. Then ask how much of the result depends on your assumptions.</p><Badge/><p className="tiny">Synthetic teaching arrays. Illustrative dates. Not NISAR observations or satellite imagery.</p><Link className="text-link" to="/time-machine"><Play size={16}/>Open the full time machine</Link></div><div className="preview-panel">{d?<><div className="preview-raster"><Raster values={d.observations[w.frame].power} width={d.width} height={d.height} label="Interactive synthetic teaching grid"/><span>T{w.frame+1} · {d.title}</span></div><Timeline/></>:<div className="empty"><p>{w.error||'Loading teaching data…'}</p>{w.error&&<button onClick={w.retry}>Retry observations</button>}</div>}</div></section>
 <section className="home-cases"><div className="section-heading"><div><h2>Three ways to investigate change</h2><p>Focused teaching cases, with different questions and honest limits.</p></div><Link to="/cases" className="text-link">Explore case studies<ArrowRight size={16}/></Link></div><div className="case-grid">{w.datasets.filter(x=>x.status==='synthetic').map(c=><Link to={`/cases/${c.id}`} className="case-card" key={c.id}><span className="tiny">{c.phenomenon}</span><h3>{c.title}</h3><p>{c.location}</p><span className="text-link">Explore teaching case<ArrowRight size={15}/></span></Link>)}</div></section><section className="home-note"><h2>Clarity is a scientific feature.</h2><p>Real NISAR metadata is available in the data catalog. The built-in analysis uses labeled synthetic fixtures. Import calibrated GCOV windows to run the same pipeline on real measurements.</p><Link className="button" to="/data">See the data provenance</Link></section></div>;}
