import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Mountain, ShieldCheck } from 'lucide-react';
import { nepalEvent } from '../../shared/nepal-event';
import { useObservatory } from '../data/observatory';
import { date, Download, External } from '../components/ui';
import './nepal-case.css';

export function NepalFeature(){return <section className="nepal-feature"><Mountain size={35}/><div><span className="tiny">Documented event · 26 August 2026</span><h2>Nepal: follow the flood evidence.</h2><p>Investigate the Rasuwa river corridor through source reports and archived NISAR observations.</p></div><Link className="button primary" to="/cases/nepal-rasuwa-2026">Explore Nepal flood<ArrowRight size={16}/></Link></section>;}

export default function NepalCase(){
 const [step,setStep]=useState(0);const {data,error,retry}=useObservatory();
 const region=data?.regions.find(r=>r.id===nepalEvent.regionId);
 const pair=['2026-08-19','2026-08-31'].map(d=>region?.observations.find(f=>f.date===d));
 const selected=nepalEvent.timeline[step],source=nepalEvent.sources.find(s=>s.id===selected.source)!;
 return <div className="page nepal-case"><Link className="text-link" to="/cases">All case studies</Link><header className="nepal-heading"><div><span className="badge observed">DOCUMENTED EVENT</span><h1>{nepalEvent.title}</h1><p className="lead">26 August 2026 · Bhote Koshi–Trishuli river corridor</p></div><Mountain size={62} aria-hidden="true"/></header>
  <p className="notice"><strong>Reported flood; no validated satellite detection.</strong> Humanitarian reports establish the event context. The radar views support visual investigation; they do not measure flood damage.</p>
  <div className="case-story"><section className="panel"><h2>What happened?</h2><p>NSET reports a mountain mass movement followed by a debris-laden flood that affected the river corridor through Rasuwa and downstream districts. UNFPA describes displacement and disruption to transport and health services.</p><p><External href={nepalEvent.sources[0].url}>Read NSET’s event account</External></p><p><External href={nepalEvent.sources[2].url}>Read UNFPA’s humanitarian report</External></p><h3>What can radar help investigate?</h3><p>Compare the appearance of river margins and nearby terrain across dates. Treat each contrast as a question to check against acquisition geometry, terrain masks, weather, and independent observations.</p></section>
  <section className="panel"><h2>Follow the reporting timeline</h2><div className="nepal-timeline" role="group" aria-label="Nepal event report timeline">{nepalEvent.timeline.map((entry,i)=><button key={entry.date} aria-pressed={step===i} onClick={()=>setStep(i)}><span>{date(entry.date)}</span><strong>{entry.title}</strong></button>)}</div><div className="nepal-timeline-detail" key={step} aria-live="polite"><h3>{selected.title}</h3><p>{selected.text}</p><External href={source.url}>{source.name}</External></div><p className="tiny">Report dates are not a simulation of flood progression.</p></section></div>
  <section className="nepal-observations"><div className="section-heading"><div><span className="tiny">Archived observations · geographic context</span><h2>Before and after the reported event</h2></div><Link className="button primary" to="/observatory?region=nepal-rasuwa">Explore Nepal radar dates<ArrowRight size={16}/></Link></div>
   {error?<div role="alert" className="notice">The observation archive could not be loaded. Event reports remain available.<button onClick={retry}>Retry Nepal imagery</button></div>:!data?<p role="status">Loading Nepal observation metadata…</p>:pair.some(f=>!f)?<p className="notice">The required Nepal image pair is not in this archive. No replacement imagery is shown.</p>:<div className="nepal-image-pair">{pair.map((frame,i)=><figure key={frame!.id}><img src={frame!.image} alt={`Actual NISAR false-color view of the Rasuwa study region on ${date(frame!.date)}; not a flood classification`} loading="lazy"/><figcaption><strong>{i===0?'Before':'After'} · {date(frame!.date)}</strong><span>{i===0?'7 days before the reported event':'5 days after the reported event'}</span><External href={frame!.request}>Exact NASA image request</External></figcaption></figure>)}</div>}
   <p className="tiny">Same requested geographic bounds. Matching catalog records share track/frame, mode, and processing identifier; daily mosaic composition can still differ. These views do not isolate the event’s cause.</p>
  </section>
  <div className="case-story"><section className="panel"><h2><ShieldCheck size={20}/> What the evidence does not show</h2><ul>{nepalEvent.limitations.map(l=><li key={l}>{l}</li>)}</ul></section><section className="panel"><h2>How to investigate responsibly</h2><ol><li>Start with the dated reports and distinguish reported impacts from image interpretation.</li><li>Open Nepal radar dates, select a reference acquisition, and use synchronized comparison.</li><li>Inspect source metadata and terrain-related uncertainty before identifying a possible change.</li><li>Use calibrated products, quality masks, and independent validation before estimating any flood extent.</li></ol><Link to="/methodology">Read the numerical methodology</Link><p className="tiny">The separate analysis lab uses synthetic teaching data; it is not a Nepal flood result.</p></section></div>
  <section className="panel nepal-evidence"><h2>Sources and evidence</h2><p>Editorial source review: {date(nepalEvent.reviewed)}. This is an archived investigation, not a live emergency service.</p>{nepalEvent.sources.map(s=><div key={s.id}><External href={s.url}>{s.name}</External><p>{s.role}</p></div>)}<Download label="Export Nepal case evidence" name="sarflow-nepal-rasuwa-2026.json" value={{...nepalEvent,observationRegion:region??null,quantitativeResult:null}}/></section>
 </div>;
}
