import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowLeftRight, ArrowRight, Database, Download as DownloadIcon, Eye, FileText, Layers, MapPin, Pause, Play, Search, ShieldCheck, SkipBack, SkipForward, X } from 'lucide-react';
import { useObservatory } from '../data/observatory';
import { selectionReport } from '../../shared/observatory';
import type { Observatory as ObservatoryArchive, Region } from '../../shared/observatory';
import { date, Download, Empty, External } from '../components/ui';
import './observatory.css';
import Investigation from '../components/Investigation';
import ChangeTracker from '../components/ChangeTracker';
import ArchiveCompare from '../components/ArchiveCompare';
import { visualInvestigation } from '../../shared/investigation';
import '../components/radar-story.css';
const ObservationMap=lazy(()=>import('../components/ObservationMap'));

export default function Observatory(){
 const {data,error,retry}=useObservatory();
 const [params,setParams]=useSearchParams();
 const region=data?.regions.find(r=>r.id===params.get('region'))??data?.regions.find(r=>r.id==='brahmaputra')??data?.regions[0];
 if(error)return <Empty title="Real observation archive unavailable" retry={retry}>{error} <Link to="/explore">Open the teaching lab</Link></Empty>;
 if(!data||!region)return <div className="empty" role="status">Loading actual NISAR observation archive…</div>;
 return <RegionWorkspace key={region.id} data={data} region={region} choose={id=>setParams({region:id})}/>;
}

export function RegionWorkspace({data,region,choose}:{data:ObservatoryArchive;region:Region;choose:(id:string)=>void}){
 const [index,setIndex]=useState(region.observations.length-1),[reference,setReference]=useState(0);
 const [playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1);
 const [studio,setStudio]=useState<'swipe'|'split'|'opacity'>('swipe'),[lens,setLens]=useState('processed');
 const [compare,setCompare]=useState(false),[split,setSplit]=useState(50),[opacity,setOpacity]=useState(1),[footprint,setFootprint]=useState(false);
 const [query,setQuery]=useState(''),[status,setStatus]=useState('Loading observations'),[point,setPoint]=useState<[number,number]|null>(null),[note,setNote]=useState('');
 const [archiveView,setArchiveView]=useState(false);
 const evidence=useRef<HTMLDialogElement>(null);
 const frame=region?.observations[Math.min(index,region.observations.length-1)];
 const before=region?.observations[Math.min(reference,region.observations.length-1)];
 useEffect(()=>{
  if(!playing||!status.endsWith('imagery loaded'))return;
  const timer=setTimeout(()=>{if(index>=region.observations.length-1)setPlaying(false);else{setStatus('Loading observation');setIndex(index+1);}},2200/speed);
  return()=>clearTimeout(timer);
 },[playing,speed,region,index,status]);
 useEffect(()=>{const hide=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 const report=selectionReport(data,region,reference,index,note);
 return <div className="observatory">
  <div className="observatory-header"><div><span className="obs-kicker"><span/>NISAR observation workspace</span><h1>Earth, in motion.</h1></div><div className="actions"><Link className="button" to="/global-radar">Animate another place</Link><Link className="button" to="/world">World imagery</Link><Link className="obs-lab-link" to="/explore">Numerical analysis lab<ArrowRight size={15}/></Link><button onClick={()=>evidence.current?.showModal()}><ShieldCheck size={16}/>Evidence</button></div></div>
  <section className="notice"><strong>Investigate {region.name}, one evidence level at a time.</strong><p>These archived radar colors support visual comparison. Calibrated GCOV measurements and terrain validity are required for experimental water candidates; neither flood cause nor accuracy is established here.</p><div className="actions"><button aria-pressed={archiveView} onClick={()=>{setPlaying(false);setArchiveView(v=>!v);}}>{archiveView?'Return to geographic map':'Use archived image viewer'}</button><Link className="button" to="/water">Check calibrated water analysis</Link></div></section>
  <ol className="workflow-steps" aria-label="Investigation workflow"><li>1 · Location selected</li><li>2 · {region.observations.length} observations</li><li aria-current={!compare?'step':undefined}>3 · Select time</li><li aria-current={compare?'step':undefined}>4 · Compare dates</li><li>5 · Detection: calibrated data required</li><li>6 · Explain & inspect receipts</li></ol>
  {region.id==='nepal-rasuwa'&&<p className="notice">Nepal flood investigation · reported event: 26 August 2026. Visual changes are not validated flood detections. <Link to="/cases/nepal-rasuwa-2026">Read event reports and limitations</Link></p>}<div className="observatory-body">
   <aside className="observation-sidebar">
    <div className="obs-sidebar-section"><div className="section-heading"><h2>Study regions</h2><span className="count-pill">{data.regions.length}</span></div><label className="obs-search"><Search size={16}/><input aria-label="Find a prepared region" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a prepared region"/></label>
     <div className="region-list">{data.regions.filter(r=>`${r.name} ${r.country}`.toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.id} className={r.id===region.id?'selected':''} aria-pressed={r.id===region.id} onClick={()=>choose(r.id)}><img src={r.observations.at(-1)!.thumbnail??r.observations.at(-1)!.image} alt="" loading="lazy"/><span><strong>{r.name}</strong><small>{r.country}</small></span><ArrowRight size={14}/></button>)}</div>
     {!data.regions.some(r=>`${r.name} ${r.country}`.toLowerCase().includes(query.toLowerCase()))&&<p className="tiny">No archived region matches. This search covers the prepared archive regions.</p>}
    </div>
    <div className="obs-sidebar-section"><h2><Layers size={16}/>Observation layers</h2><div className="actual-layer"><div className="layer-icon"><Database size={19}/></div><div><strong>NISAR L-SAR</strong><small>GCOV · false-color daily mosaic</small></div><span className="real-pill">Actual</span></div><label className="range-label">Radar opacity <strong>{Math.round(opacity*100)}%</strong><input type="range" aria-label="Radar opacity" disabled={archiveView} min="0" max="1" step="0.05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><label className="check"><input type="checkbox" disabled={archiveView} checked={footprint} onChange={e=>setFootprint(e.target.checked)}/>Matching granule footprint</label><p className="tiny">{archiveView?'Opacity, footprint and coordinate inspection require the geographic map.':'Outline may extend beyond this prepared view.'}</p></div>
    <div className="obs-sidebar-section"><div className="section-heading"><h2>Acquisition archive</h2><span className="count-pill">{region.observations.length}</span></div><div className="acquisition-list">{region.observations.map((f,i)=><button key={f.id} className={i===index?'selected':''} aria-pressed={i===index} onClick={()=>{setIndex(i);setPlaying(false);}}><span className="acquisition-dot"/><span><strong>{date(f.date)}</strong><small>{f.acquired.slice(11,19)} UTC · GCOV</small></span><span className="tiny">T{i+1}</span></button>)}</div></div>
    <div className="obs-sidebar-footer"><ShieldCheck size={16}/><p>{frame.sha256?'Archived NASA imagery.':'On-demand NASA imagery.'}<br/>No generated satellite scenes.</p><External href="https://hyp3-docs.asf.alaska.edu/nisar-docs/worldview/">Product guide</External></div>
   </aside>
   <section className="observation-stage" aria-label="Real NISAR imagery explorer">
    <div className="obs-stage-toolbar"><div><MapPin size={16}/><strong>{region.name}</strong><span>{region.topic}</span></div><div className="obs-view-modes"><button className={!compare?'selected':''} aria-pressed={!compare} onClick={()=>setCompare(false)}><Eye size={15}/>Observe</button><button className={compare?'selected':''} aria-pressed={compare} onClick={()=>{setPlaying(false);setCompare(true);}}><ArrowLeftRight size={15}/>Compare</button></div></div>
    <div className="lens-guide"><strong>Change Lens</strong><div className="actions"><button disabled title="Raw radar samples are not included in this browse collection">Raw observation — unavailable</button><button aria-pressed={lens==='processed'&&!compare} onClick={()=>{setLens('processed');setCompare(false);}}>Processed observation</button><button aria-pressed={compare} onClick={()=>{setCompare(true);setPlaying(false);setLens('comparison');}}>Before / after</button><button disabled title="Requires calibrated power arrays; RGB differences are not scientific measurements">Difference — calibrated data required</button><button disabled title="No validated detection is available from the displayed RGB imagery">Detected change — unavailable</button><button aria-pressed={lens==='uncertainty'} onClick={()=>{setLens('uncertainty');setPlaying(false);}}>Uncertainty</button></div>{lens==='uncertainty'&&<p role="status">Confidence is not estimated. Missing pixels, changing acquisition modes, mosaic composition and environmental conditions can alter the view. Inspect the receipts below; the map remains a processed visualization.</p>}<button disabled={index===0} onClick={()=>{setReference(index-1);setCompare(true);setPlaying(false);setLens('comparison');}}>Compare previous observation</button></div>
    <div className="obs-map-wrap">{archiveView?<ArchiveCompare frame={frame} before={before} compare={compare} split={split} mode={studio} onStatus={setStatus}/>:<Suspense fallback={<div className="empty">Loading the geographic canvas…</div>}><ObservationMap region={region} frame={frame} before={before} compare={compare} mode={studio} split={studio==='split'?50:split} opacity={opacity} footprint={footprint} onStatus={setStatus} onPoint={setPoint}/></Suspense>}<div className="obs-image-label"><span className="real-pill">Actual NISAR imagery</span><strong key={`${frame.id}-${compare}`}>{compare?`${date(before.date)} / ${date(frame.date)}`:date(frame.date)}</strong><span>False-color visualization · not optical imagery</span></div><div className="obs-north" aria-hidden="true">N ↑</div><div className="obs-coordinates">{archiveView?`Archived bounds: ${region.bounds.join(', ')}`:point?`${point[1].toFixed(5)}°, ${point[0].toFixed(5)}°`:'Click anywhere on the map to inspect coordinates'}</div></div>
    {compare&&<div className="real-compare-controls"><label>Studio mode<select aria-label="Comparison studio mode" value={studio} onChange={e=>setStudio(e.target.value as typeof studio)}><option value="swipe">Swipe</option><option value="split">Split screen</option><option value="opacity">Opacity blend</option></select></label><label>Reference date<select aria-label="Reference acquisition" value={reference} onChange={e=>setReference(Number(e.target.value))}>{region.observations.map((f,i)=><option key={f.id} value={i}>{date(f.date)}</option>)}</select></label><label>{studio==='opacity'?'After image opacity':'Swipe comparison'}<input disabled={studio==='split'} type="range" aria-label="Real imagery swipe" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))}/></label><span className="tiny">Left / base: reference date. Right / overlay: selected date. {archiveView?'Fixed archived bounds.':'Shared zoom and pan.'}<br/>{reference===index?'Same acquisition selected on both sides.':'Visual comparison only; no numerical detection.'}</span></div>}
    <div className="obs-play-progress" data-running={playing&&status.endsWith('imagery loaded')} aria-hidden="true"><span key={`${index}-${playing}-${status}-${speed}`} style={{animationDuration:`${2200/speed}ms`}}/></div><div className="observation-timebar"><div className="obs-player"><button aria-label="Previous acquisition" disabled={index===0} onClick={()=>{setPlaying(false);setIndex(index-1);}}><SkipBack size={16}/></button><button className="primary" aria-label={playing?'Pause observations':'Play observations'} onClick={()=>{if(!playing&&index===region.observations.length-1)setIndex(0);setCompare(false);setPlaying(!playing);}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label="Next acquisition" disabled={index===region.observations.length-1} onClick={()=>{setPlaying(false);setIndex(index+1);}}><SkipForward size={16}/></button><select aria-label="Observation playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="0.5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select></div><div className="real-timeline"><input type="range" aria-label="Real acquisition timeline" min="0" max={region.observations.length-1} value={index} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/><div>{region.observations.map((f,i)=><button key={f.id} className={i===index?'selected':''} onClick={()=>{setPlaying(false);setIndex(i);}}>{date(f.date)}</button>)}</div></div><span className="obs-frame-number">{index+1}<small>/ {region.observations.length}</small></span></div>
    <div className="observation-status"><span role="status"><i/>{status}</span><span>NASA GIBS / ASF · {frame.sha256?'archived':'queried'} {date(data.retrieved)}</span><button onClick={()=>evidence.current?.showModal()}>View processing & source<FileText size={13}/></button></div>
   </section>
  </div>
  <ChangeTracker region={region} before={reference} after={index} onCompare={(a,b)=>{setPlaying(false);setReference(a);setIndex(b);setCompare(true);setLens('comparison');}}/>
  <section className="observation-insights"><article><span className="tiny">Read the signal</span><h2>What am I seeing?</h2><p>{region.description}</p><div className="rgb-key"><span><i style={{background:'#156aa2'}}/>Low-return appearances</span><span><i style={{background:'#579b43'}}/>Vegetated appearances</span><span><i style={{background:'#bc8430'}}/>Structural contrasts</span></div><p className="tiny">Illustrative color interpretation, not land-cover classes. Acquisition mode and moisture can alter the colors.</p></article><article><span className="tiny">Keep your interpretation separate</span><h2>Investigation notes</h2><label className="sr-only" htmlFor="observation-note">Your visual interpretation</label><textarea id="observation-note" value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} placeholder="Describe what you notice. What additional evidence would you need?"/><div className="actions"><Download label="Export investigation" name={`sarflow-${region.id}-investigation.json`} value={{...report,inspectedCoordinate:point}}/><span className="tiny">Includes source URLs, image hashes, dates, and your note.</span></div></article><article className="observation-limit"><ShieldCheck size={23}/><h2>Seeing change isn’t proving its cause.</h2><p>These are real radar visualizations. Their colors cannot be converted back into calibrated dB measurements. Use the analysis lab for reproducible numerical methods, or connect reviewed GCOV power data.</p><Link to="/explore">Open numerical analysis lab<ArrowRight size={15}/></Link></article></section>
  <Investigation value={visualInvestigation(data,region,reference,index)}/>
  <dialog ref={evidence} className="evidence observation-evidence" aria-labelledby="real-evidence-title"><div className="drawer-head"><ShieldCheck/><h2 id="real-evidence-title">Real observation evidence</h2><button aria-label="Close observation evidence" onClick={()=>evidence.current?.close()}><X size={20}/></button></div><span className="badge observed">{frame.sha256?'ARCHIVED NISAR VISUALIZATION':'ON-DEMAND NISAR VISUALIZATION'}</span><dl className="metadata"><dt>Source</dt><dd>{data.source}</dd><dt>Collection</dt><dd>{data.collection}</dd><dt>Acquisition</dt><dd>{frame.acquired}</dd><dt>Matching granule</dt><dd>{frame.id}</dd><dt>Product identifier</dt><dd>{frame.title}</dd><dt>Display layer</dt><dd>{data.layer}</dd><dt>Requested bounds</dt><dd>{region.bounds.join(', ')}</dd><dt>Display raster</dt><dd>{new URL(frame.request).searchParams.get('WIDTH')} × {new URL(frame.request).searchParams.get('HEIGHT')} PNG · geographic WMS</dd><dt>SHA-256</dt><dd>{frame.sha256??'Not captured · on-demand NASA image'}</dd></dl><p>Source → calibrated GCOV products → NASA false-color daily mosaic → bounded WMS image → geographic display. No quantitative change is computed from PNG values.</p><h3>Interpretation limits</h3><ul>{data.limitations.map(l=><li key={l}>{l}</li>)}</ul><div className="evidence-source-links"><External href={frame.source}>Matching NASA CMR record</External><External href={frame.request}>Exact NASA image request</External><External href={region.query}>Reproduce catalog search</External><a href={frame.image} download><DownloadIcon size={15}/>Download original archived PNG</a></div><div className="actions"><Download label="Export observation evidence" name={`sarflow-${region.id}-evidence.json`} value={report}/></div></dialog>
 </div>;
}
