import { ArrowRight, ArrowUpRight, Fingerprint, GitCompareArrows, Satellite } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useObservatory } from '../data/observatory';
import { date } from '../components/ui';
import './real-home.css';
import RadarStory from '../components/RadarStory';
import { NepalFeature } from './NepalCase';
export default function RealHome(){
 const {data,error,retry}=useObservatory();const lead=data?.regions.find(r=>r.id==='brahmaputra');const frame=lead?.observations.at(-1);
 return <div className="real-home"><section className="real-hero"><div className="real-hero-copy"><span className="mission-tag"><span/>Earth observation, with evidence.</span><h1>See Earth<br/>Move.</h1><p>Follow rivers, landscapes, and cities through actual NISAR radar observations. Move through time. Compare what you see. Know where every image came from.</p><div className="actions"><Link className="button primary" to="/observatory">Explore real observations<ArrowRight size={17}/></Link><Link className="button" to="/world">Explore the whole world</Link></div><a className="radar-watch-link" href="#radar-story">Watch radar in motion <ArrowRight size={15}/></a><div className="real-hero-proof"><Satellite size={18}/><div><strong>NASA–ISRO Synthetic Aperture Radar</strong><span>GCOV imagery · archived acquisitions · source-linked</span></div></div></div><Link className="real-hero-scene" to="/observatory?region=brahmaputra" aria-label="Explore Brahmaputra NISAR imagery"><img src={frame?.image??'/images/nisar-seattle.jpg'} alt={frame?'Actual NISAR false-color view of the Brahmaputra river and surrounding Bangladesh landscape':'NASA NISAR context view of Seattle'}/><div className="real-scene-top"><span>{frame?'Actual NISAR observation':'NASA context image'}</span><ArrowUpRight size={22}/></div><div className="real-scene-bottom"><span>{frame?'Brahmaputra floodplain':'NISAR Views Seattle'}</span><strong>{frame?date(frame.date):'NASA/JPL-Caltech'}</strong><small>False-color radar visualization · not optical imagery</small></div></Link></section>
 <NepalFeature/><section className="nepal-feature"><div><h2>Animate any place with available radar dates.</h2><p>Search worldwide and play a real NISAR observation sequence.</p></div><Link className="button primary" to="/global-radar">Animate Earth</Link></section><RadarStory/><section className="real-entry-strip"><div><strong>Observe.</strong><span>Explore georeferenced radar imagery.</span></div><div><strong>Compare.</strong><span>Swipe between actual acquisition dates.</span></div><div><strong>Investigate.</strong><span>Keep interpretation connected to evidence.</span></div></section>
 <section className="real-region-section"><div className="section-heading"><div><span className="tiny">Start with a place</span><h2>Earth doesn’t tell just one story.</h2></div><Link className="text-link" to="/observatory">Open observation workspace<ArrowRight size={16}/></Link></div>{error?<div className="notice" role="alert">{error}<button onClick={retry}>Retry archive</button></div>:!data?<p role="status">Loading archived study regions…</p>:<div className="real-region-grid">{data.regions.map(r=><Link className="real-region-card" to={`/observatory?region=${r.id}`} key={r.id}><div className="real-region-image"><img src={r.observations.at(-1)!.thumbnail??r.observations.at(-1)!.image} alt={`${r.name}, actual NISAR false-color imagery`} loading="lazy"/><span>{r.observations.length} archived dates</span></div><div className="real-region-copy"><span>{r.topic}</span><h3>{r.name}<ArrowUpRight size={20}/></h3><p>{r.country}</p><small>{date(r.observations[0].date)} — {date(r.observations.at(-1)!.date)}</small></div></Link>)}</div>}</section>
 <section className="real-product-section"><div><GitCompareArrows size={26}/><h2>Time is part of the map.</h2><p>Play the acquisition sequence, choose a reference date, and compare both views with synchronized zoom and pan. Inspect coordinates and export your investigation.</p><Link className="text-link" to="/observatory">Open the time workspace<ArrowRight size={15}/></Link></div><div><Fingerprint size={26}/><h2>Every image has a paper trail.</h2><p>Inspect the NASA request, matching acquisition record, processing layer, and file hash. Real imagery and synthetic analysis are clearly separated.</p><Link className="text-link" to="/data">Explore data provenance<ArrowRight size={15}/></Link></div><div className="real-lab-card"><span className="badge">SYNTHETIC TEACHING LAB</span><h2>Go deeper into the numbers.</h2><p>Learn log-ratio change detection, test thresholds, inspect uncertainty, and reproduce the calculations. No numerical measurements are invented from radar colors.</p><Link className="button" to="/explore">Open analysis lab<ArrowRight size={15}/></Link></div></section>
 <div className="real-home-credit">Built around “Dancing with the SARs” · NASA Space Apps 2026 brief. Independent project; no NASA or ISRO endorsement.</div></div>;
}
