import { useState } from 'react';
import { spatialProfile } from '../../shared/investigation';
import { temporalMeans } from '../../shared/analysis';
import { useWorkspace } from '../data/Workspace';
import { date } from './ui';
export function TemporalChart(){
 const w=useWorkspace(),d=w.dataset;if(!d)return null;const values=temporalMeans(d),finite=values.filter(Number.isFinite),min=finite.length?Math.floor(Math.min(...finite))-1:-1,max=finite.length?Math.ceil(Math.max(...finite))+1:1;
 const y=(v:number)=>115-(v-min)/(max-min)*88,x=(i:number)=>42+i*400/(values.length-1);
 return <div className="chart"><div className="section-heading"><h3>Backscatter through time</h3><span className="tiny">Mean linear power → dB</span></div><svg viewBox="0 0 480 152" role="img" aria-label="Temporal mean backscatter; exact values in the table below"><title>Mean power of valid cells, converted to dB</title>{[min,(min+max)/2,max].map(v=><g key={v}><line x1="38" x2="460" y1={y(v)} y2={y(v)} stroke="var(--line)"/><text x="2" y={y(v)+4}>{v.toFixed(0)}</text></g>)}{values.map((v,i)=>Number.isFinite(v)?<g key={i}>{i>0&&Number.isFinite(values[i-1])&&<line x1={x(i-1)} y1={y(values[i-1])} x2={x(i)} y2={y(v)} stroke="var(--accent)" strokeWidth="2.5"/>}<circle cx={x(i)} cy={y(v)} r={i===w.frame?6:3.5} fill={i===w.frame?'var(--accent)':'var(--surface)'} stroke="var(--accent)" strokeWidth="2"/>{(values.length<=8||i===w.frame||i===0||i===values.length-1)&&<text x={x(i)} y="143" textAnchor="middle">T{i+1}</text>}</g>:null)}</svg><p className="tiny">All dates use their common valid pixel intersection. An empty intersection produces no mean.</p><details><summary>Accessible data table</summary><table><thead><tr><th>Acquisition</th><th>Mean (dB)</th></tr></thead><tbody>{values.map((v,i)=><tr key={i}><td>{date(d.observations[i].date)}</td><td>{Number.isFinite(v)?v.toFixed(3):'No valid cells'}</td></tr>)}</tbody></table></details></div>;
}
export function Histogram(){const {result:r}=useWorkspace();if(!r)return null;const max=Math.max(...r.histogram.map(b=>b.count));return <div className="chart"><h3>Distribution of change</h3><p className="tiny">Cell counts by Δ backscatter (dB). End bins include tails.</p><svg viewBox="0 0 480 156" role="img" aria-label="Histogram of pairwise change; exact bin counts in the table"><title>Distribution of log-ratio values</title>{r.histogram.map((b,i)=><g key={b.label}><rect x={i*39+5} y={120-b.count/max*100} width="30" height={b.count/max*100} fill={i<6?'#386ca4':'#b67528'}/><text x={i*39+20} y="142" textAnchor="middle">{i===0?'<−5':i===11?'≥5':i-6}</text></g>)}</svg><details><summary>Histogram data table</summary><table><thead><tr><th>Change bin (dB)</th><th>Cells</th></tr></thead><tbody>{r.histogram.map(b=><tr key={b.label}><td>{b.label}</td><td>{b.count}</td></tr>)}</tbody></table></details></div>;}

export function SpatialProfile(){
 const {dataset:d,result:r}=useWorkspace(),[selected,setSelected]=useState(0);if(!d||!r)return null;
 const row=Math.min(selected,d.height-1),profile=spatialProfile(r.delta,d.width,d.height,row),finite=profile.flatMap(p=>p.value===null?[]:[p.value]);
 const extent=Math.max(1,...finite.map(Math.abs)),x=(column:number)=>40+column*400/(d.width-1),y=(v:number)=>80-v/extent*60;
 return <section className="panel"><h2>Spatial profile</h2><p className="tiny">Per-cell log-ratio across raster row {row+1}. Horizontal position is column index, not ground distance. Gaps are excluded cells.</p><label>Profile row<input aria-label="Spatial profile row" type="range" min="0" max={d.height-1} value={row} onChange={e=>setSelected(Number(e.target.value))}/></label><svg viewBox="0 0 480 175" role="img" aria-label="Signed change in dB along the selected raster row; exact values in the table"><line x1="40" x2="440" y1="80" y2="80" stroke="var(--line)"/><text x="4" y="24">+{extent.toFixed(1)}</text><text x="4" y="144">−{extent.toFixed(1)}</text>{profile.map((p,i)=>p.value===null?null:<g key={i}>{i>0&&profile[i-1].value!==null&&<line x1={x(i-1)} y1={y(profile[i-1].value!)} x2={x(i)} y2={y(p.value)} stroke="var(--accent)" strokeWidth="2"/>}<circle cx={x(i)} cy={y(p.value)} r="2" fill="var(--accent)"/></g>)}<text x="40" y="168">Column 1</text><text x="360" y="168">Column {d.width}</text></svg><details><summary>Profile values, source & method</summary><p>Source: {d.id}, current before/after pair. Method: same common-mask log-ratio and filtering settings as the analysis above. Unit: dB.</p><div className="profile-table"><table><thead><tr><th>Column</th><th>Change (dB)</th></tr></thead><tbody>{profile.map(p=><tr key={p.column}><td>{p.column+1}</td><td>{p.value===null?'Excluded':p.value.toFixed(4)}</td></tr>)}</tbody></table></div></details></section>;
}
