import { useEffect, useRef, useState } from 'react';
import type * as ml from 'maplibre-gl';
import type { Observatory } from '../../shared/observatory';
import { coverageSchema, type Coverage } from '../../shared/coverage';
import { External } from './ui';

export default function WorldLayers({map,archive,latitude,longitude,locationName}:{locationName?:string;map:ml.Map|null;archive:Observatory|null;latitude:number;longitude:number}){
 const locationLabel=locationName??'Finding location name...';
 const [date,setDate]=useState(''),[dates,setDates]=useState<string[]>([]),[datesBusy,setDatesBusy]=useState(true),[datesError,setDatesError]=useState(''),[revision,setRevision]=useState(0);
 const [coverage,setCoverage]=useState<Coverage|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Coverage not queried. The optical globe does not indicate NISAR availability.');
 const [outlines,setOutlines]=useState(true),[fill,setFill]=useState(true),[events,setEvents]=useState(true);
 const request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 useEffect(()=>{
  const c=new AbortController();request.current?.abort();setBusy(false);setCoverage(null);setDate('');setDates([]);setDatesBusy(true);setDatesError('');setMessage('Select an available date to load global footprints.');
  const timer=setTimeout(()=>{void fetch(`/api/coverage/dates?lat=${latitude}&lon=${longitude}`,{signal:c.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.error);if(!Array.isArray(body.dates)||body.dates.some((d:unknown)=>typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)))throw Error('Invalid date response');return body.dates as string[];}).then(values=>{if(!c.signal.aborted){setDates(values);setDate(values[0]??'');}}).catch(e=>{if(!c.signal.aborted)setDatesError(e.message);}).finally(()=>{if(!c.signal.aborted)setDatesBusy(false);});},500);
  return()=>{clearTimeout(timer);c.abort();};
 },[latitude,longitude,revision]);
 async function load(){request.current?.abort();const c=new AbortController();request.current=c;setBusy(true);setCoverage(null);setMessage('Querying NASA acquisition footprints…');try{const r=await fetch(`/api/coverage?date=${date}`,{signal:c.signal});const body=await r.json();if(!r.ok)throw Error(body.error);const result=coverageSchema.parse(body);if(c.signal.aborted)return;setCoverage(result);setMessage(result.records.length?`${result.records.length} footprints shown${result.total!==null?` of ${result.total} catalog records`:''}. ${result.truncated?'Partial sample; omissions are not absence of coverage.':'Catalog outlines do not guarantee pixel coverage.'}`:result.total===0?'NO OBSERVATION AVAILABLE FOR THIS DATE in the queried collection. This is not a mission-wide absence claim.':'No drawable outlines returned. Records may lack supported geometry; this does not establish absence of observations.');}catch(e){if(!c.signal.aborted)setMessage(e instanceof Error?e.message:'Coverage unavailable. Retry.');}finally{if(!c.signal.aborted)setBusy(false);}}
 useEffect(()=>{
  if(!map)return;
  function update(){
   if(!map)return;if(!map.isStyleLoaded()){map.once('idle',update);return;}
   const geo={type:'FeatureCollection' as const,features:(coverage?.records??[]).map(r=>({type:'Feature' as const,properties:{id:r.id},geometry:{type:'Polygon' as const,coordinates:[r.polygon]}}))};
   const points={type:'FeatureCollection' as const,features:(archive?.regions??[]).map(r=>({type:'Feature' as const,properties:{event:r.id==='nepal-rasuwa',name:r.name},geometry:{type:'Point' as const,coordinates:r.center}}))};
   const selected={type:'FeatureCollection' as const,features:Number.isFinite(latitude)&&Number.isFinite(longitude)&&Math.abs(latitude)<=90&&Math.abs(longitude)<=180?[{type:'Feature' as const,properties:{},geometry:{type:'Point' as const,coordinates:[longitude,latitude]}}]:[]};
   for(const [id,data] of [['catalog-coverage',geo],['study-events',points],['selected-location',selected]] as const){const source=map.getSource(id) as ml.GeoJSONSource|undefined;if(source)source.setData(data);else map.addSource(id,{type:'geojson',data});}
   if(!map.getLayer('coverage-fill'))map.addLayer({id:'coverage-fill',type:'fill',source:'catalog-coverage',paint:{'fill-color':'#59c1df','fill-opacity':.16}});
   if(!map.getLayer('coverage-outline'))map.addLayer({id:'coverage-outline',type:'line',source:'catalog-coverage',paint:{'line-color':'#80daf2','line-width':1.5}});
   if(!map.getLayer('study-points'))map.addLayer({id:'study-points',type:'circle',source:'study-events',paint:{'circle-radius':['case',['get','event'],8,5],'circle-color':['case',['get','event'],'#f4bd66','#ffffff'],'circle-stroke-color':'#172c3e','circle-stroke-width':2}});
   if(!map.getLayer('selection-point'))map.addLayer({id:'selection-point',type:'circle',source:'selected-location',paint:{'circle-radius':9,'circle-color':'#176c97','circle-stroke-color':'#ffffff','circle-stroke-width':3}});
   map.setLayoutProperty('coverage-fill','visibility',fill?'visible':'none');map.setLayoutProperty('coverage-outline','visibility',outlines?'visible':'none');map.setLayoutProperty('study-points','visibility',events?'visible':'none');
  }
  update();map.on('load',update);return()=>{map.off('load',update);map.off('idle',update);};
 },[map,coverage,archive,latitude,longitude,fill,outlines,events]);
 return <section className="world-layer-controls"><h2>Observation coverage</h2><p className="coverage-location"><strong>{locationLabel}</strong></p><label>Available acquisition dates<select aria-label="Coverage date" disabled={datesBusy||!dates.length} value={date} onChange={e=>{request.current?.abort();setBusy(false);setDate(e.target.value);setCoverage(null);setMessage('Date changed. Load footprints to inspect this date.');}}>{!dates.length&&<option value="">{datesBusy?'Loading available dates...':datesError?'Dates unavailable':'No available dates'}</option>}{dates.map(d=><option key={d} value={d}>{locationLabel} ? {new Date(d+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}</option>)}</select></label>{datesError&&<p role="alert">{datesError} <button onClick={()=>setRevision(v=>v+1)}>Retry available dates</button></p>}{!datesBusy&&!datesError&&!dates.length&&<p>No observation dates returned for this location.</p>}<p className="tiny">Dates from the latest 100 matching NASA catalog records at the selected point. Footprints loaded below are a global sample for that date; catalog presence does not guarantee valid pixels.</p><button disabled={busy||!date} onClick={()=>void load()}>{busy?'Loading footprints…':'Load dated footprints'}</button><p role="status">{message}</p><label className="check"><input type="checkbox" checked={outlines} onChange={e=>setOutlines(e.target.checked)}/>Granule outlines</label><label className="check"><input type="checkbox" checked={fill} onChange={e=>setFill(e.target.checked)}/>Catalog coverage shading</label><label className="check"><input type="checkbox" checked={events} onChange={e=>setEvents(e.target.checked)}/>Prepared studies & reported event</label><p className="tiny">Cyan outlines/shading: queried granules. White dots: prepared studies. Amber dot: reported Nepal flood, not a radar detection. Blue/white dot: selected location.</p>{coverage&&<details><summary>Coverage receipts & map alternative</summary><p>{coverage.collection}. Retrieved {coverage.retrieved}. Up to 100 records; invalid or antimeridian-crossing outlines omitted.</p><External href={coverage.query}>Reproduce NASA query</External><ul>{coverage.records.map(r=><li key={r.id}><External href={r.source}>{r.acquired} — {r.id}</External></li>)}</ul></details>}</section>;
}
