import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[],network=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('requestfailed',r=>{if(!r.failure()?.errorText.includes('ERR_ABORTED'))network.push({url:r.url(),error:r.failure()?.errorText});});
await page.goto('http://127.0.0.1:5187/');
await page.getByRole('heading',{name:'See Earth Move.'}).waitFor();
await page.screenshot({path:'artifacts/home-production.png',fullPage:true});
const timing=await page.evaluate(()=>({navigation:performance.getEntriesByType('navigation')[0].toJSON(),paint:performance.getEntriesByType('paint').map(e=>e.toJSON()),transferBytes:performance.getEntriesByType('resource').reduce((n,e)=>n+e.transferSize,0)}));
await page.getByRole('link',{name:'Explore real observations',exact:true}).click();
await page.getByText('Archived imagery loaded',{exact:true}).waitFor();
await page.screenshot({path:'artifacts/observatory-production.png',fullPage:true});
await page.getByRole('button',{name:'Compare',exact:true}).click();
await page.getByText('Archived imagery loaded',{exact:true}).waitFor();
await page.screenshot({path:'artifacts/observatory-comparison.png',fullPage:true});
await page.goto('http://127.0.0.1:5187/explore');
await page.locator('.maplibregl-canvas').waitFor();
await page.waitForTimeout(1200);
if(await page.locator('.map-error').count())throw Error(await page.locator('.map-error').innerText());
await page.getByRole('button',{name:'Run analysis',exact:true}).click();
await page.getByRole('button',{name:'Uncertainty',exact:true}).click();
await page.screenshot({path:'artifacts/explore-production.png',fullPage:true});
await page.getByRole('link',{name:'Change analysis',exact:true}).click();
await page.getByText('Cells above threshold',{exact:true}).waitFor();
await page.screenshot({path:'artifacts/analysis-production.png',fullPage:true});
await page.getByRole('button',{name:'Switch to dark theme'}).click();
const a11y=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();
await page.screenshot({path:'artifacts/analysis-dark.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:5187/');
await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});
const report={testedAt:new Date().toISOString(),environment:'Local Windows Chrome; no CPU/network throttling; production server',timing,errors,network,darkThemeViolations:a11y.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}))};
await fs.writeFile('artifacts/browser-audit.json',JSON.stringify(report,null,2));
console.log(JSON.stringify({paint:timing.paint.map(p=>({name:p.name,ms:p.startTime})),transferBytes:timing.transferBytes,errors,network,darkThemeViolations:report.darkThemeViolations},null,2));
await browser.close();
if(errors.length||network.length||report.darkThemeViolations.length)process.exitCode=1;
